<a href="https://colab.research.google.com/github/AndrewPiasecki/PythonCourse/blob/main/Andrew_Piasecki_Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Problem 1

For the following questions, the file data_extended.csv is provided, which contains a list of stocks (similar to S&P 500) and certain data about each. Use pandas read_csv() to load the file into a DataFrame, and for each part below, develop statements to further refine the data.

In [1]:
import pandas as pd

# Assuming the file is in the same directory as your script
df = pd.read_csv('/content/sample_data/data_extended.csv')
df

,Symbol,Company Name,SEC Filings,Headquarters Location,Date First Added,Founded
0,AAPL,Apple Inc.,link1,"Cupertino, CA",1982-11-30,1976
1,GOOGL,Alphabet Inc.,link2,"Mountain View, CA",2006-04-03,1998
2,MSFT,Microsoft Corp.,link3,"Redmond, WA",NaN,1975
3,AMZN,Amazon.com Inc.,link4,"Seattle, WA",2005-11-18,NaN
4,FB,"Facebook, Inc.",link5,"Menlo Park, CA",2013-12-23;2014-03-21,2004;2012
...,...,...,...,...,...,...
195,AAPL,Apple Inc.,link196,"Cupertino, CA",1982-11-30,1976
196,GOOGL,Alphabet Inc.,link197,"Mountain View, CA",2006-04-03,1998
197,MSFT,Microsoft Corp.,link198,"Redmond, WA",NaN,1975
198,AMZN,Amazon.com Inc.,link199,"Seattle, WA",2005-11-18,NaN
199,FB,"Facebook, Inc.",link200,"Menlo Park, CA",2013-12-23;2014-03-21,2004;2012

a) SEC filings: Use the drop() method to take out the SEC filings column from the DataFrame.

In [3]:
# a) Drop the SEC filings column

df = df.drop('SEC Filings', axis = 'columns')
df

,Symbol,Company Name,Headquarters Location,Date First Added,Founded
0,AAPL,Apple Inc.,"Cupertino, CA",1982-11-30,1976
1,GOOGL,Alphabet Inc.,"Mountain View, CA",2006-04-03,1998
2,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975
3,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN
4,FB,"Facebook, Inc.","Menlo Park, CA",2013-12-23;2014-03-21,2004;2012
...,...,...,...,...,...
195,AAPL,Apple Inc.,"Cupertino, CA",1982-11-30,1976
196,GOOGL,Alphabet Inc.,"Mountain View, CA",2006-04-03,1998
197,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975
198,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN
199,FB,"Facebook, Inc.","Menlo Park, CA",2013-12-23;2014-03-21,2004;2012

b) Headquarters location: Use the split() method to create two new fields, one for city and one for state.

In [7]:
# b) Split Headquarters Location into city and state

df[['City', 'State']] = df['Headquarters Location'].str.split(',', expand = True)
df

,Symbol,Company Name,Headquarters Location,Date First Added,Founded,City,State
0,AAPL,Apple Inc.,"Cupertino, CA",1982-11-30,1976,Cupertino,CA
1,GOOGL,Alphabet Inc.,"Mountain View, CA",2006-04-03,1998,Mountain View,CA
2,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
3,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA
4,FB,"Facebook, Inc.","Menlo Park, CA",2013-12-23;2014-03-21,2004;2012,Menlo Park,CA
...,...,...,...,...,...,...,...
195,AAPL,Apple Inc.,"Cupertino, CA",1982-11-30,1976,Cupertino,CA
196,GOOGL,Alphabet Inc.,"Mountain View, CA",2006-04-03,1998,Mountain View,CA
197,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
198,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA
199,FB,"Facebook, Inc.","Menlo Park, CA",2013-12-23;2014-03-21,2004;2012,Menlo Park,CA


c) Date first added missing values: Create a DataFrame that has the symbols with those stocks where the Date first added field is missing a value.

In [11]:
# c) Date first added missing values
missing_date_added =df[df['Date First Added'].isnull()]
missing_date_added

,Symbol,Company Name,Headquarters Location,Date First Added,Founded,City,State
2,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
7,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
12,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
17,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
22,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
27,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
32,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
37,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
42,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
47,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
52,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
57,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
62,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
67,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
72,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
77,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
82,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
87,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
92,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
97,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
102,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
107,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
112,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
117,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
122,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
127,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
132,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
137,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
142,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
147,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
152,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
157,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
162,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
167,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
172,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
177,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
182,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
187,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
192,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA
197,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA

d) Date first added (multivalued): Find rows where “Date first added” is different from a single date, then use statements to create a new column that determines and populates the date in first position if more than one date is indicated for this field.

In [14]:
# d) Date first added (multivalued)
# Assuming the separation by semicolon for multivalued fields

def firstDate(date):
  if isinstance(date, str):
    return date.split(';')[0]
  else:
    return date

df['First Date Added'] = df['Date First Added'].apply(firstDate)
df

,Symbol,Company Name,Headquarters Location,Date First Added,Founded,City,State,First Date Added
0,AAPL,Apple Inc.,"Cupertino, CA",1982-11-30,1976,Cupertino,CA,1982-11-30
1,GOOGL,Alphabet Inc.,"Mountain View, CA",2006-04-03,1998,Mountain View,CA,2006-04-03
2,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA,NaN
3,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
4,FB,"Facebook, Inc.","Menlo Park, CA",2013-12-23;2014-03-21,2004;2012,Menlo Park,CA,2013-12-23
...,...,...,...,...,...,...,...,...
195,AAPL,Apple Inc.,"Cupertino, CA",1982-11-30,1976,Cupertino,CA,1982-11-30
196,GOOGL,Alphabet Inc.,"Mountain View, CA",2006-04-03,1998,Mountain View,CA,2006-04-03
197,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA,NaN
198,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
199,FB,"Facebook, Inc.","Menlo Park, CA",2013-12-23;2014-03-21,2004;2012,Menlo Park,CA,2013-12-23

 e) Founded (missing values): Create a DataFrame that has the symbols with those stocks where the Founded column is missing a value.

In [18]:
# e) Founded (missing values)
missing_founded = df[df['Founded'].isnull()]
missing_founded

,Symbol,Company Name,Headquarters Location,Date First Added,Founded,City,State,First Date Added
3,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
8,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
13,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
18,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
23,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
28,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
33,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
38,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
43,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
48,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
53,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
58,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
63,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
68,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
73,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
78,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
83,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
88,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
93,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
98,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
103,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
108,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
113,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
118,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
123,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
128,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
133,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
138,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
143,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
148,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
153,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
158,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
163,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
168,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
173,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
178,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
183,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
188,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
193,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18
198,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18

f) Founded (multivalued): Find rows where “Date first added” is different from a single date, then use statements to create a new column that determines and populates the date in first position if more than one date is indicated for this field.

In [19]:
# f) Founded (multivalued) - similar approach as part d
# Note: The problem statement for 'f' seems to repeat the requirement for 'd'. Assuming it meant to process the 'Founded' field.

def firstPosition(date):
  if isinstance(date, str):
    return date.split(';')[0]
  else:
    return date

df['Founded Added'] = df['Founded'].apply(firstPosition)
df

,Symbol,Company Name,Headquarters Location,Date First Added,Founded,City,State,First Date Added,Founded Added
0,AAPL,Apple Inc.,"Cupertino, CA",1982-11-30,1976,Cupertino,CA,1982-11-30,1976
1,GOOGL,Alphabet Inc.,"Mountain View, CA",2006-04-03,1998,Mountain View,CA,2006-04-03,1998
2,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA,NaN,1975
3,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18,NaN
4,FB,"Facebook, Inc.","Menlo Park, CA",2013-12-23;2014-03-21,2004;2012,Menlo Park,CA,2013-12-23,2004
...,...,...,...,...,...,...,...,...,...
195,AAPL,Apple Inc.,"Cupertino, CA",1982-11-30,1976,Cupertino,CA,1982-11-30,1976
196,GOOGL,Alphabet Inc.,"Mountain View, CA",2006-04-03,1998,Mountain View,CA,2006-04-03,1998
197,MSFT,Microsoft Corp.,"Redmond, WA",NaN,1975,Redmond,WA,NaN,1975
198,AMZN,Amazon.com Inc.,"Seattle, WA",2005-11-18,NaN,Seattle,WA,2005-11-18,NaN
199,FB,"Facebook, Inc.","Menlo Park, CA",2013-12-23;2014-03-21,2004;2012,Menlo Park,CA,2013-12-23,2004

## Problem 2
S&P  Price Data

For the following questions, the files data-extended.csv and sp-prices.csv are provided, which contain a list of stocks in the S&P 500 and certain data about each. For the constituent data, Symbol is a unique key column. For the prices data, Symbol and Date together uniquely define a row.

a) Use read_csv() to load two files, data_extended.csv and sp-prices.csv, each into their own DataFrame.

In [22]:
import pandas as pd

# a) Load the two files into their own DataFrame
constituents = pd.read_csv('/content/sample_data/data_extended.csv')
prices = pd.read_csv('/content/sample_data/sp-prices.csv')

In [23]:
constituents

,Symbol,Company Name,SEC Filings,Headquarters Location,Date First Added,Founded
0,AAPL,Apple Inc.,link1,"Cupertino, CA",1982-11-30,1976
1,GOOGL,Alphabet Inc.,link2,"Mountain View, CA",2006-04-03,1998
2,MSFT,Microsoft Corp.,link3,"Redmond, WA",NaN,1975
3,AMZN,Amazon.com Inc.,link4,"Seattle, WA",2005-11-18,NaN
4,FB,"Facebook, Inc.",link5,"Menlo Park, CA",2013-12-23;2014-03-21,2004;2012
...,...,...,...,...,...,...
195,AAPL,Apple Inc.,link196,"Cupertino, CA",1982-11-30,1976
196,GOOGL,Alphabet Inc.,link197,"Mountain View, CA",2006-04-03,1998
197,MSFT,Microsoft Corp.,link198,"Redmond, WA",NaN,1975
198,AMZN,Amazon.com Inc.,link199,"Seattle, WA",2005-11-18,NaN
199,FB,"Facebook, Inc.",link200,"Menlo Park, CA",2013-12-23;2014-03-21,2004;2012

In [24]:
prices

    Symbol        Date        Price
0     AAPL  2020-09-30  1019.408078
1     AAPL  2020-10-31  1083.113589
2    GOOGL  2020-09-30  1053.395287
3    GOOGL  2020-10-31  1039.266000
4     MSFT  2020-09-30  1000.005628
..     ...         ...          ...
395   MSFT  2020-10-31  1090.422971
396   AMZN  2020-09-30  1030.220262
397   AMZN  2020-10-31  1013.793274
398     FB  2020-09-30  1064.330011
399     FB  2020-10-31  1032.997575

[400 rows x 3 columns]

b) Rotate data: Transform the data organization for the price DataFrame, so prices for each date are each in their own dated column: for example, price-20201031, price-20200930, and so on.

In [ ]:
# b) Rotate data

c) Join data: Use join() to combine the constituents data and rotated price data from part (b) into one DataFrame. The resulting DataFrame should have one row for each row in the constituents data.

In [ ]:
# c) Join data
# Ensure that the index is set to 'Symbol' for the join operation

d) Augment data: Add a column that is the difference between the price on the last available date and the price on the prior available date.

In [ ]:
# d) Augment data with price difference between the last and prior available dates

e) Missing values: Determine which stocks do not have price data.

In [ ]:

# e) Missing values - Determine which stocks do not have price data
missing_price_data = combined_df[combined_df['price-2020-10-31'].isna()]

Empty DataFrame
Columns: [Company Name, Sector, price-2020-09-30, price-2020-10-31, price-diff]
Index: []